;;; SPDX-License-Identifier: GPL-3.0-or-later
;;;
;;; SPDX-FileCopyrightText: 2024 Murilo <murilo@disroot.org>
;;; SPDX-FileCopyrightText: 2026 Andrew Tropin <andrew@trop.in>

(define-module (nonrde packages terminals)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages base)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages haskell-xyz)
  #:use-module (gnu packages image)
  #:use-module (gnu packages ncurses)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages textutils)
  #:use-module (gnu packages vulkan)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages zig)
  #:use-module (guix build-system zig)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:use-module (guix utils))


;;; Applications.

(define-public ghostty
  (package
    (name "ghostty")
    (version "1.3.1")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/ghostty-org/ghostty")
             (commit (string-append "v" version))))
       (file-name (git-file-name name version))
       (sha256
        (base32 "0d064l17drqcf6bc27jmjxak0n2xqp2mpalakwp3j9mx8yclrmzr"))))
    (build-system zig-build-system)
    (arguments
     (list #:tests? #f
           #:install-source? #f
           #:zig zig-0.15
           #:zig-release-type "fast"
           #:zig-build-flags
           #~(list "-Dcpu=baseline"
                   "--prefix"
                   ""
                   "--system"
                   (string-append (getenv "TMPDIR") "/source/zig-cache")
                   "--search-prefix"
                   (ungexp (this-package-input "libadwaita"))
                   "--search-prefix"
                   (ungexp (this-package-input "bzip2"))
                   "-Dpatch-rpath="
                   "-Dgtk-x11=true"
                   "-Dgtk-wayland=true"
                   (string-append "-Dversion-string=" #$version))
           #:modules
           '((guix build zig-build-system)
             (guix build utils)
             (ice-9 match))
           #:phases
           #~(modify-phases %standard-phases
               (delete 'validate-runpath)
               (add-after 'install 'patch-install-files
                 (lambda _
                   (with-directory-excursion #$output
                     (substitute*
                         (list "share/applications/com.mitchellh.ghostty.desktop"
                               "share/dbus-1/services/com.mitchellh.ghostty.service"
                               "lib/systemd/user/app-com.mitchellh.ghostty.service")
                       (("/bin/ghostty")
                        (string-append #$output "/bin/ghostty"))))))
               (add-after 'unpack 'patch-ghostty-exe
                 (lambda _
                   (substitute* "src/build/SharedDeps.zig"
                     (("\"bzip2\"")
                      "\"bz2\""))
                   (substitute* "src/build/GhosttyExe.zig"
                     ((".addExecutable[(][.][{]" all)
                      (string-append all "\n\t.use_lld = false,\n")))))
               (add-after 'unpack 'unpack-zig
                 (lambda _
                   (for-each
                    (match-lambda
                      ((dst src)
                       (let* ((dest (string-append "zig-cache/" dst)))
                         (mkdir-p dest)
                         (if (or (string-suffix? ".tar.gz" src)
                                 (string-suffix? ".tgz" src)
                                 (string-suffix? ".tar.xz" src)
                                 (string-suffix? ".tar.zst" src))
                             (invoke "tar" "-xf" src "-C" dest "--strip-components=1")
                             (copy-recursively src dest)))))
                    ;; autogenerated from build.zig.zon.json
                    `(("uucode-0.1.0-ZZjBPj96QADXyt5sqwBJUnhaDYs_qBeeKijZvlRa0eqM"
                       #$(origin (method git-fetch)
                                 (uri (git-reference (url "https://github.com/jacobsandlund/uucode")
                                                     (commit "5f05f8f83a75caea201f12cc8ea32a2d82ea9732")))
                                 (file-name (git-file-name  "uucode" "5f05f8f83a75"))
                                 (sha256 (base64 "sHPh+TQSdUGus/QTbj7KSJJkTuNTrK4VNmQDjS30Lf8="))))
                      ("N-V-__8AANT61wB--nJ95Gj_ctmzAtcjloZ__hRqNw5lC1Kr" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/DearBindings_v0.17_ImGui_v1.92.5-docking.tar.gz") (sha256 (base64 "i/7FAOAJJvZ5hT7iPWfMOS08MYFzPKRwRzhlHT9wuqM="))))
                      ("N-V-__8AALw2uwF_03u4JRkZwRLc3Y9hakkYV7NKRR9-RIZJ" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/breakpad-b99f444ba5f6b98cac261cbb391d8766b34a5918.tar.gz") (sha256 (base64 "bMqYlD0amQdmzvYQd8Ca/1k4Bj/heh7+EijlQSttatk="))))
                      ("N-V-__8AAIrfdwARSa-zMmxWwFuwpXf1T3asIN7s5jqi9c1v" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/fontconfig-2.14.2.tar.gz") (sha256 (base64 "O6LdkhWHGKzsXKrxpxYEO1qgVcJ7CB2RSvPMtA3OilU="))))
                      ("N-V-__8AAKLKpwC4H27Ps_0iL3bPkQb-z6ZVSrB-x_3EEkub" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/freetype-1220b81f6ecfb3fd222f76cf9106fecfa6554ab07ec7fdc4124b9bb063ae2adf969d.tar.gz") (sha256 (base64 "QnIB9dUVFnDQXB9bRb713aHy592XHvVPD+qqf/0quQw="))))
                      ("N-V-__8AADcZkgn4cMhTUpIz6mShCKyqqB-NBtf_S2bHaTC-" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/gettext-0.24.tar.gz") (sha256 (base64 "yRhQPVk9cNr0hE0XWhPYFq+stmfAb7oeydzVACwVGLc="))))
                      ("N-V-__8AABzkUgISeKGgXAzgtutgJsZc0-kkeqBBscJgMkvy" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/glslang-12201278a1a05c0ce0b6eb6026c65cd3e9247aa041b1c260324bf29cee559dd23ba1.tar.gz") (sha256 (base64 "FKLtu1Ccs+UamlPj9eQ12/WXFgS0uDPmPmB26MCpl7U="))))
                      ("gobject-0.3.0-Skun7ANLnwDvEfIpVmohcppXgOvg_I6YOJFmPIsKfXk-" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/gobject-2025-11-08-23-1.tar.zst") (sha256 (base64 "2b1DBvAIHY5LhItq3+q9L6tJgi7itnnrSAHc7fXWDEg="))))
                      ("N-V-__8AALiNBAA-_0gprYr92CjrMj1I5bqNu0TSJOnjFNSr" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/gtk4-layer-shell-1.1.0.tar.gz") (sha256 (base64 "mChCgSYKXu9bT2OlXxbEv2p4ihAgptsDfssPcfozaYg="))))
                      ("N-V-__8AAG02ugUcWec-Ndp-i7JTsJ0dgF8nnJRUInkGLG7G" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/harfbuzz-11.0.0.tar.xz") (sha256 (base64 "8WNRuv4hRyX+LB1bWfDZPkmQWkskeJn7kNcM/5U6K5s="))))
                      ("N-V-__8AAGmZhABbsPJLfbqrh6JTHsXhY6qCaLAQyx25e0XE" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/highway-66486a10623fa0d72fe91260f96c892e41aceb06.tar.gz") (sha256 (base64 "h9T4iT704I8iSXNgj/6/lCaKgTgLp5wS6IQZaMgKohI="))))
                      ("N-V-__8AAEbOfQBnvcFcCX2W5z7tDaN8vaNZGamEQtNOe0UI" #$(origin (method url-fetch) (uri "https://github.com/ocornut/imgui/archive/refs/tags/v1.92.5-docking.tar.gz") (sha256 (base64 "yBbCDox18+Fa6Gc1DnmSVQLRpqhZOLsac7iSfl8x+cs="))))
                      ("N-V-__8AABVbAwBwDRyZONfx553tvMW8_A2OKUoLzPUSRiLF" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/ghostty-themes-release-20260216-151611-fc73ce3.tgz") (sha256 (base64 "FCALuGoMgUq2lgnVALKAs5a20uuDXt8Gdt5KeJwKqP0="))))
                      ("N-V-__8AAIC5lwAVPJJzxnCAahSvZTIlG-HhtOvnM1uh-66x" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/JetBrainsMono-2.304.tar.gz") (sha256 (base64 "xXppHouCrQmLWWPzlZAy5AOPORCHr3cViFulkEYQXMQ="))))
                      ("N-V-__8AAJrvXQCqAT8Mg9o_tk6m0yf5Fz-gCNEOKLyTSerD" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/libpng-1220aa013f0c83da3fb64ea6d327f9173fa008d10e28bc9349eac3463457723b1c66.tar.gz") (sha256 (base64 "/syVtGzwXo4/yKQUdQ4LparQDYnp/fF16U/wQcrxoDo="))))
                      ("libxev-0.0.0-86vtc4IcEwCqEYxEYoN_3KXmc6A9VLcm22aVImfvecYs" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/libxev-34fa50878aec6e5fa8f532867001ab3c36fae23e.tar.gz") (sha256 (base64 "YAPqa5bkpRihKPkyMn15oRvTCZaxO3O66ymRY3lIfdc="))))
                      ("N-V-__8AAG3RoQEyRC2Vw7Qoro5SYBf62IHn3HjqtNVY6aWK" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/libxml2-2.11.5.tar.gz") (sha256 (base64 "bCgFni4+60K1tLFkieORamNGwQladP7jvGXNxdiaYhU="))))
                      ("N-V-__8AAMVLTABmYkLqhZPLXnMl-KyN38R8UVYqGrxqO26s" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/NerdFontsSymbolsOnly-3.4.0.tar.gz") (sha256 (base64 "EWTRuVbUveJI17LwmYxDzJT1ICQxoVZKeTiVsec7DQQ="))))
                      ("N-V-__8AAHjwMQDBXnLq3Q2QhaivE0kE2aD138vtX2Bq1g7c" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/oniguruma-1220c15e72eadd0d9085a8af134904d9a0f5dfcbed5f606ad60edc60ebeccd9706bb.tar.gz") (sha256 (base64 "ABqhIC54RI9MC/GkjHblVodrNvFtks4yB+zP1h2Z8qA="))))
                      ("N-V-__8AADYiAAB_80AWnH1AxXC0tql9thT-R-DYO1gBqTLc" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/pixels-12207ff340169c7d40c570b4b6a97db614fe47e0d83b5801a932dcd44917424c8806.tar.gz") (sha256 (base64 "Veg7FtCRCCUCvxSb9FfzH0IJLFmCZQ4/+657SIcb8Ro="))))
                      ("N-V-__8AAKYZBAB-CFHBKs3u4JkeiT4BMvyHu3Y5aaWF3Bbs" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/plasma_wayland_protocols-12207e0851c12acdeee0991e893e0132fc87bb763969a585dc16ecca33e88334c566.tar.gz") (sha256 (base64 "XFi6IUrNjmvKNCbcCLAixGqN2Zeymhs+KLrfccIN9EE="))))
                      ("N-V-__8AAPlZGwBEa-gxrcypGBZ2R8Bse4JYSfo_ul8i2jlG" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/sentry-1220446be831adcca918167647c06c7b825849fa3fba5f22da394667974537a9c77e.tar.gz") (sha256 (base64 "KsZJfMjWGo0xCT5HrduMmyxFsWsHBbszSoNbZCPDGN8="))))
                      ("N-V-__8AANb6pwD7O1WG6L5nvD_rNMvnSc9Cpg1ijSlTYywv" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/spirv_cross-1220fb3b5586e8be67bc3feb34cbe749cf42a60d628d2953632c2f8141302748c8da.tar.gz") (sha256 (base64 "tStvz8Ref6abHwahNiwVVHNETizAmZVVaxVsU7pmV+M="))))
                      ("N-V-__8AAHffAgDU0YQmynL8K35WzkcnMUmBVQHQ0jlcKpjH" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/utfcpp-1220d4d18426ca72fc2b7e56ce47273149815501d0d2395c2a98c726b31ba931e641.tar.gz") (sha256 (base64 "/8ZooxDndgfTk/PBizJxXyI9oerExNbgV5oR345rWc8="))))
                      ("uucode-0.2.0-ZZjBPqZVVABQepOqZHR7vV_NcaN-wats0IB6o-Exj6m9" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/uucode-0.2.0-ZZjBPqZVVABQepOqZHR7vV_NcaN-wats0IB6o-Exj6m9.tar.gz") (sha256 (base64 "0KvuD0+L1urjwFF3fhbnxC2JZKqqAVWRxOVlcD9GX5U="))))
                      ("vaxis-0.5.1-BWNV_LosCQAGmCCNOLljCIw6j6-yt53tji6n6rwJ2BhS" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/vaxis-7dbb9fd3122e4ffad262dd7c151d80d863b68558.tar.gz") (sha256 (base64 "LnIzK8icW1Qexua9SHaeHz+3V8QAbz0a+UC1T5sIjvY="))))
                      ("N-V-__8AAKrHGAAs2shYq8UkE6bGcR1QJtLTyOE_lcosMn6t" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/wayland-9cb3d7aa9dc995ffafdbdef7ab86a949d0fb0e7d.tar.gz") (sha256 (base64 "6kGR1o5DdnflHzqs3ieCmBAUTpMdOXoyfcYDXiw5xQ0="))))
                      ("N-V-__8AAKw-DAAaV8bOAAGqA0-oD7o-HNIlPFYKRXSPT03S" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/wayland-protocols-258d8f88f2c8c25a830c6316f87d23ce1a0f12d9.tar.gz") (sha256 (base64 "XO3K3egbdeYPI+XoO13SuOtO+5+Peb16NH0UiusFMPg="))))
                      ("N-V-__8AAAzZywE3s51XfsLbP9eyEw57ae9swYB9aGB6fCMs" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/wuffs-122037b39d577ec2db3fd7b2130e7b69ef6cc1807d68607a7c232c958315d381b5cd.tar.gz") (sha256 (base64 "nkzSCr6W5sTG7enDBXEIhgEm574uLD41UVR2wlC+HBM="))))
                      ("z2d-0.10.0-j5P_Hu-6FgBsZNgwphIqh17jDnj8_yPtD8yzjO6PpHRQ" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/z2d-0.10.0-j5P_Hu-6FgBsZNgwphIqh17jDnj8_yPtD8yzjO6PpHRQ.tar.gz") (sha256 (base64 "afIdou/V7gk3/lXE0J5Ir8T7L5GgHvFnyMJ1rgRnl/c="))))
                      ("zf-0.10.3-OIRy8RuJAACKA3Lohoumrt85nRbHwbpMcUaLES8vxDnh" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/zf-3c52637b7e937c5ae61fd679717da3e276765b23.tar.gz") (sha256 (base64 "OwFdkorwTp4mJyvBXrTbtNmp1GnrbSkKDdrmc7d8RWg="))))
                      ("zig_js-0.0.0-rjCAV-6GAADxFug7rDmPH-uM_XcnJ5NmuAMJCAscMjhi" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/zig_js-04db83c617da1956ac5adc1cb9ba1e434c1cb6fd.tar.gz") (sha256 (base64 "TCAY5WAV05UEuAkDhq2c6Tk/ODgAhdnDI3O/flb8c6M="))))
                      ("zig_objc-0.0.0-Ir_Sp5gTAQCvxxR7oVIrPXxXwsfKgVP7_wqoOQrZjFeK" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/zig_objc-f356ed02833f0f1b8e84d50bed9e807bf7cdc0ae.tar.gz") (sha256 (base64 "3YSvc3YlNW/NciyzCQnzsujXAmZ89XlxSqfqvArAjsw="))))
                      ("wayland-0.5.0-dev-lQa1khrMAQDJDwYFKpdH3HizherB7sHo5dKMECfvxQHe" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/zig_wayland-1b5c038ec10da20ed3a15b0b2a6db1c21383e8ea.tar.gz") (sha256 (base64 "TxRrc17Q1Sf1IOO/cdPpP3LD0PpYOujt06SFH3B5Ek4="))))
                      ("zigimg-0.1.0-8_eo2vHnEwCIVW34Q14Ec-xUlzIoVg86-7FU2ypPtxms" #$(origin (method url-fetch) (uri "https://github.com/ivanstepanovftw/zigimg/archive/d7b7ab0ba0899643831ef042bd73289510b39906.tar.gz") (sha256 (base64 "LB7Xa6KzVRRUSwwnyWM+y6fDG+kIDjfnoBDJO1obxVM="))))
                      ("N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o" #$(origin (method url-fetch) (uri "https://deps.files.ghostty.org/zlib-1220fed0c74e1019b3ee29edae2051788b080cd96e90d56836eea857b0b966742efb.tar.gz") (sha256 (base64 "F+iIY/NgBnKrSRgvIXKBtvxNPHYr3jYZNeQ2qVIU0Fw=")))))))))))
    (native-inputs
     (list `(,glib "bin")
           blueprint-compiler
           gettext-minimal ;; msgfmt
           ncurses/tinfo
           pandoc
           pkg-config
           zstd
           gobject-introspection
           libxml2 ;; xmllint
           tar))
    (inputs
     (list bzip2
           expat
           fontconfig
           glslang
           harfbuzz
           libadwaita
           libglvnd
           libpng
           libx11
           libxcursor
           libxi
           libxrandr
           oniguruma
           gtk4-layer-shell
           zlib))
    (native-search-paths
     ;; FIXME: This should only be located in 'ncurses'.  Nonetheless it is
     ;; provided for usability reasons.  See <https://bugs.gnu.org/22138>.
     (list (search-path-specification
            (variable "TERMINFO_DIRS")
            (files '("share/terminfo")))))
    (synopsis "Fast, native, feature-rich terminal emulator pushing modern features")
    (description "Ghostty is a terminal emulator that differentiates itself by
being fast, feature-rich, and native.  While there are many excellent terminal
emulators available, they all force you to choose between speed, features, or
native UIs.  Ghostty provides all three.")
    (home-page "https://ghostty.org")
    (license license:expat)))
